config/routes.rb
HHeroes::Application.routes.draw do
  
  
  resources :friendships
  resources :messages
  resources :fields
  resources :quarters
  resources :courses
  resources :buildings

  mount Forem::Engine, :at => "/forums"
  devise_for :users, :controllers => {:registrations => "registrations", confirmations: "confirmations"}

  resources :users

#  root :to => 'navigation#homepage'
  root :to => 'navigation#alt_homepage'
  
  match 'new_topics' => 'topics#new_topics'
  
  match 'homepage' => 'navigation#alt_homepage'
  match 'hot_topics' => 'navigation#hot_topics'
  match 'newest_topics' => 'navigation#newest_topics'
  match 'building_leaders' => 'navigation#building_leaders'
  match 'add_major_minor' => 'navigation#add_major_minor'
  match 'top_posters' => 'navigation#top_posters'
  match 'sandbox' => 'navigation#sandbox'
  match 'update_courses' => 'navigation#update_courses'
  match 'about' => 'navigation#about'
  match 'roadmap' => 'navigation#roadmap'

  match 'my_messages' => 'messages#my_messages'
  match 'create_message' => 'messages#create'
  match 'view_message' => 'messages#view_message'
  match 'reply_to_message' => 'messages#reply_to_message'
  match 'trash_message' => 'messages#trash_message'
  match 'restore_message' => 'messages#restore_message'
  match 'destroy_message' => 'messages#destroy'
  
  match 'user_profile' => 'users#alt_profile'
  match 'alt_profile' => 'users#alt_profile'
  match 'classmates' => 'users#classmates'
  match 'modify_profile' => 'users#modify_profile'
  match 'add_major_minors' => 'users#add_major_minors'
  match 'add_friend' => 'friendships#create'

  match 'destroy_quarter' => 'quarters#destroy'
  match 'list_fields' => 'fields#list'
  match 'input_course_data' => 'courses#add_data'
  
  match 'my_library' => 'library#my_library'  
  match 'add_book' => 'library#add_book'  
  match 'destroy_book' => 'library#destroy'  
  match 'find_trades' => 'library#find_trades'  
  match 'find_books' => 'library#find_books'  
  match 'three_way_trades' => 'library#three_way_trades'  
  match 'manage_textbooks' => 'library#manage_textbooks'  
  
  match 'list_courses' => 'courses#list'
  match 'add_course_to_quarter' => 'courses#add_course_to_quarter'
  match 'remove_course_from_quarter' => 'courses#remove_course_from_quarter'
  match 'manage_classes' => 'courses#manage_classes'

  match 'building_page' => 'buildings#building_page'

  
#  match 'add_courses' => 'courses#add_data'
#  match 'add_buildings' => 'buildings#add_data'

  
  
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :user_id
  
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  # GET /friendships
  # GET /friendships.json
  def index
	@user = current_user
    @friendships = Friendship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friendships }
    end
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/new
  # GET /friendships/new.json
  def new
    @friendship = Friendship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friendship }
    end
  end

  # GET /friendships/1/edit
  def edit
    @friendship = Friendship.find(params[:id])
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
	
    respond_to do |format|
    	if @friendship.save
    		flash.now[:notice] = "Added friend."
        format.js

    	else
    		flash.now[:error] = "Unable to add friend"
        format.js
    	end
    end
  end

  # PUT /friendships/1
  # PUT /friendships/1.json
  def update
    @friendship = Friendship.find(params[:id])

    respond_to do |format|
      if @friendship.update_attributes(params[:friendship])
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy

    flash[:notice] = "Friend removed"
	redirect_to :back
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br />
    <%= f.number_field :friend_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/create.js.erb
$("#friend_link").html("Friended.")

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h2>Friends</h2>
<ul>
	<% for friendship in @user.friendships %>
		<li>
			<%= link_to friendship.friend.username, user_profile_path(:user => friendship.friend.id) %>
			<%= link_to "remove", friendship, :method => :delete %>
		</li>
	<% end %>
</ul>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @friendship.user_id %>
</p>

<p>
  <b>Friend:</b>
  <%= @friendship.friend_id %>
</p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>