config/routes.rb
HHeroes::Application.routes.draw do
  
  
  resources :friendships
  resources :messages
  resources :fields
  resources :quarters
  resources :courses
  resources :buildings

  mount Forem::Engine, :at => "/forums"
  devise_for :users, :controllers => {:registrations => "registrations", confirmations: "confirmations"}

  resources :users

#  root :to => 'navigation#homepage'
  root :to => 'navigation#alt_homepage'
  
  match 'new_topics' => 'topics#new_topics'
  
  match 'homepage' => 'navigation#alt_homepage'
  match 'hot_topics' => 'navigation#hot_topics'
  match 'newest_topics' => 'navigation#newest_topics'
  match 'building_leaders' => 'navigation#building_leaders'
  match 'add_major_minor' => 'navigation#add_major_minor'
  match 'top_posters' => 'navigation#top_posters'
  match 'sandbox' => 'navigation#sandbox'
  match 'update_courses' => 'navigation#update_courses'
  match 'about' => 'navigation#about'
  match 'roadmap' => 'navigation#roadmap'

  match 'my_messages' => 'messages#my_messages'
  match 'create_message' => 'messages#create'
  match 'view_message' => 'messages#view_message'
  match 'reply_to_message' => 'messages#reply_to_message'
  match 'trash_message' => 'messages#trash_message'
  match 'restore_message' => 'messages#restore_message'
  match 'destroy_message' => 'messages#destroy'
  
  match 'user_profile' => 'users#alt_profile'
  match 'alt_profile' => 'users#alt_profile'
  match 'classmates' => 'users#classmates'
  match 'modify_profile' => 'users#modify_profile'
  match 'add_major_minors' => 'users#add_major_minors'
  match 'add_friend' => 'friendships#create'

  match 'destroy_quarter' => 'quarters#destroy'
  match 'list_fields' => 'fields#list'
  match 'input_course_data' => 'courses#add_data'
  
  match 'my_library' => 'library#my_library'  
  match 'add_book' => 'library#add_book'  
  match 'destroy_book' => 'library#destroy'  
  match 'find_trades' => 'library#find_trades'  
  match 'find_books' => 'library#find_books'  
  match 'three_way_trades' => 'library#three_way_trades'  
  match 'manage_textbooks' => 'library#manage_textbooks'  
  
  match 'list_courses' => 'courses#list'
  match 'add_course_to_quarter' => 'courses#add_course_to_quarter'
  match 'remove_course_from_quarter' => 'courses#remove_course_from_quarter'
  match 'manage_classes' => 'courses#manage_classes'

  match 'building_page' => 'buildings#building_page'

  
#  match 'add_courses' => 'courses#add_data'
#  match 'add_buildings' => 'buildings#add_data'

  
  
end

app/views/forem/forums/_forum.html.erb
<% if can?(:read, forum) %>
  <tr class="forum <%= cycle("odd", "even") %>">
    <td>
      <%= link_to forum.title, forum_path(forum), :class => "title" %>
      <div class='description'><%= forum.description %></div>
      <%= t('forem.forums.index.last_post') -%>
      <span class='last_post'>
          <% if last_post = forum.last_post_for(forem_user) -%>
            <%= link_to(last_post.topic, forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= last_post.user.username %> <%= t('time_ago_in_words', :time => time_ago_in_words(last_post.created_at)) -%>
          <% else %>
            <%= t('forem.forums.index.none') -%>
          <% end %>
        </span>
    </td>
    <td class="topics-count"><%= topics_count(forum) %></td>
    <td class="posts-count"><%= posts_count(forum) %></td>
    <td class="views-count"><%= forum.views_count %></td>
  </tr>
<% end %>

app/views/forem/forums/_head.html.erb
<div id='forum'>
  <h2><%= link_to t('forem.forum.forums'), forums_path %> &raquo; <%= link_to forum.category, forum.category %> &raquo; <%= link_to forum.title, forum %></h2>
  <small><%= forum.description %></small>
  <menu id='forum_topic_links'>
    <% unless @topic.try(:new_record?) %>
      <% if can? :create_topic, @forum %>
        <%= link_to t('forem.topic.links.new'), new_forum_topic_path(forum) %>
      <% end %>
    <% end %>
    <% if @topic %>
      <%= link_to t('forem.topic.links.back_to_topics'), forum_path(forum) %>
    <% end %>
    <% if can? :moderate, @forum %>
      <%= link_to t('forem.forum.moderator_tools'), forum_moderator_tools_path(forum) %>
    <% end %>
  </menu>
</div>

app/views/forem/forums/_listing.html.erb
<table id='forums' class='forums subdued' cellspacing='0'>
  <thead>
  <tr>
    <th class="desc-and-last-post"><%= t('forum', :scope => 'forem.general') %></th>
    <th class="topics-count"><%= t('topics', :scope => 'forem.general') %></th>
    <th class="posts-count"><%= t('posts', :scope => 'forem.general') %></th>
    <th class="views-count"><%= t('forem.forums.index.views') %></th>
  </tr>
  </thead>
  <tbody>
    <%= render category.forums %>
  </tbody>
</table>

app/views/forem/forums/index.html.erb
<div id='forums_container'>
	
  <h1 id='forums_title'><%= t('.title') %></h1>

  <%= render @categories %>
</div>

<br>
<footer id='admin_link'>
  <% if forem_admin? %>
    <%= link_to t("area", :scope => "forem.admin"), admin_root_path %>
  <% end %>
</footer>

app/views/forem/forums/show.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @forum } %>

<%= forem_pages_widget(@topics) %>

<table class='topics subdued' cellspacing='0'>
  <thead>
    <tr>
      <th class="icon"></th>
      <th class="byline"><%= t('forem.topic.headings.topic') -%></th>
      <th class="latest-post"><%= t('forem.topic.headings.latest') -%></th>
      <th class="posts-count"><%= t('forem.topic.headings.posts') -%></th>
      <th class="views-count"><%= t('forem.topic.headings.views') -%></th>
    </tr>
  </thead>
  <tbody>
    <% if @topics.empty? %>
      <tr><td colspan='5' align='center'><%= t('forem.topic.none') %></td></tr>
    <% end %>
    <%= render @topics %>
  </tbody>
</table>

<%= forem_pages_widget(@topics) %>